import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F7FB",
    paddingHorizontal: 20,
  },
  backButton: {
    marginTop: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#183B5C",
    marginTop: 15,
    fontFamily: "System",
  },
  subtitle: {
    fontSize: 12,
    color: "#555",
    marginTop: 8,
    lineHeight: 20,
    fontFamily: "System",
  },
  cameraWrapper: {
    marginTop: 25,
    alignSelf: "center",
    width: 350,
    height: 350,
    borderRadius: 30,
    overflow: "hidden",
    backgroundColor: "#000",
    elevation: 8,
  },
  camera: {
    flex: 1,
  },
  faceGuide: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "#fff",
    alignSelf: "center",
    top: 45,
    marginLeft: 50,
  },
  idGuide: {
    position: "absolute",
    width: 110,
    height: 60,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#FFD700",
    bottom: 40,
    left: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  idText: {
    color: "#FFD700",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  securityBox: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    backgroundColor: "#E8F5E9",
    padding: 12,
    borderRadius: 12,
  },
  securityText: {
    marginLeft: 8,
    fontSize: 13,
    color: "#2E7D32",
    flex: 1,
    fontFamily: "System",
  },
  buttonContainer: {
    marginTop: 10,
    alignItems: "center",
  },
  captureButton: {
    width: 75,
    height: 75,
    borderRadius: 50,
    backgroundColor: "#183B5C",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
  },
  innerCircle: {
    width: 55,
    height: 55,
    borderRadius: 50,
    backgroundColor: "#fff",
  },
  primaryBtn: {
    backgroundColor: "#183B5C",
    paddingVertical: 14,
    paddingHorizontal: 50,
    borderRadius: 30,
    marginTop: 10,
    elevation: 4,
  },
  primaryText: {
    color: "#fff",
    fontWeight: "600",
    fontFamily: "System",
  },
  secondaryBtn: {
    paddingVertical: 10,
  },
  secondaryText: {
    color: "#183B5C",
    fontWeight: "600",
    fontFamily: "System",
  },
  permissionBtn: {
    marginTop: 15,
    backgroundColor: "#183B5C",
    padding: 12,
    borderRadius: 10,
  },
  permissionText: {
    color: "#fff",
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});
